spring:
  jpa:
    hibernate:
      ddl-auto: update

management:
  opentelemetry:
    tracing.export.otlp.endpoint: http://localhost:4318/v1/traces
    logging.export.otlp.endpoint: http://localhost:4318/v1/logs
