spring:
  application:
    name: osugachabot

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

discord:
  token: ${DISCORD_BOT_TOKEN}